# Generated by Django 5.0.2 on 2024-03-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_Name', models.CharField(max_length=100)),
                ('Student_Age', models.IntegerField()),
                ('Password', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=50)),
                ('Student_Address', models.CharField(max_length=50)),
                ('Courses', models.CharField(max_length=50)),
            ],
        ),
    ]
