# Generated by Django 5.0.2 on 2024-03-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project7app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_age', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('student_address', models.CharField(max_length=50)),
                ('courses', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentForm',
        ),
    ]
